// Mirrors prisma/seed.ts seedBillingPlans() — keep these numbers in sync with
// the actual seeded BillingPlan rows.
export const PRICING_PLANS = [
  {
    tier: 'STARTER',
    name: 'Starter',
    description: 'For solo distributors and small shops',
    monthlyPrice: 2500,
    annualPrice: 25000,
    setupFee: 20000,
    maxUsers: '5',
    popular: false,
    features: [
      'Up to 5 users',
      'Unlimited distributors & clients',
      '1 invoice template',
      'Custom branding',
      'Multiple dashboards',
    ],
  },
  {
    tier: 'PRO',
    name: 'Pro',
    description: 'For growing businesses with basic AI needs',
    monthlyPrice: 6000,
    annualPrice: 60000,
    setupFee: 20000,
    maxUsers: '15',
    popular: false,
    features: [
      'Up to 15 users',
      'AI assistant & inventory AI',
      '200,000 AI tokens / month',
      '3 invoice templates',
      'Custom branding',
      'Multiple dashboards',
    ],
  },
  {
    tier: 'BUSINESS',
    name: 'Business',
    description: 'For mid-size distribution networks',
    monthlyPrice: 12000,
    annualPrice: 120000,
    setupFee: 20000,
    maxUsers: '50',
    popular: true,
    features: [
      'Up to 50 users',
      'AI assistant & inventory AI',
      '1,000,000 AI tokens / month',
      'Per-user AI quotas',
      'Unlimited invoice templates',
      'Custom domain',
      'Priority support',
    ],
  },
  {
    tier: 'ENTERPRISE',
    name: 'Enterprise',
    description: 'For large operations with multi-region needs',
    monthlyPrice: null,
    annualPrice: null,
    setupFee: null,
    maxUsers: 'Unlimited',
    popular: false,
    features: [
      'Unlimited users',
      'Custom AI token allocation',
      'Per-user AI quotas',
      'Unlimited invoice templates',
      'Custom domain',
      'Priority support',
      '99.9% uptime SLA',
      'Dedicated onboarding',
    ],
  },
] as const

export { TRIAL_DAYS } from '@/lib/billing/constants'
